# 自动关闭不规范PR
name: AutocloserPR
on:
  pull_request_target:
    types: [opened, edited]

jobs:
  Autoclose:
    runs-on: ubuntu-latest
    if: github.repository == 'RayWangQvQ/BiliBiliToolPro'
    steps:
    - uses: roots/issue-closer@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-close-message: "This PR was automatically closed because it did not meet the requirements, please check the requirements."
        pr-pattern: ".*请问您是否明白：【yes】 -->.*"

  checkTargetBranch:
    runs-on: ubuntu-latest
    needs: Autoclose
    steps:
      - uses: Vankka/pr-target-branch-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: main
          change-to: develop
          comment: |
              Your PR was set to `main`, but PRs should be sent to `develop`
              The base branch of this PR has been automatically changed to `develop`, please check that there are no merge conflicts.
