name: No Response

on:
  # workflow_dispatch:
  issue_comment:
    types: [created]
  schedule:
    - cron: '7 4,10 * * *'

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ github.token }}
          # closeComment: This issue has been automatically closed due to no response from the original author. Please feel free to reopen it if you have more information that can help us investigate the issue further.
          daysUntilClose: 3
          responseRequiredLabel: needs-more-info
