name: Tag

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag:
    name: add tag
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get current version
        id: current_version
        run: |
          version=$(grep -oP '(?<=<Version>).*?(?=<\/Version>)' ./scripts/common.props)
          echo "Curent version: $version"
          echo "current_version=$version" >> $GITHUB_OUTPUT

      - name: Tag and push
        run: |
          git tag "$new_tag"
          git push origin "$new_tag"
